version: "3.9"

services:

  neo4j:
    image: neo4j
    volumes:
      - ./data:/data
     # - ./logs:/logs # Uncomment this to record Neo4j Logging data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/gradvek1
      NEO4J_server_memory_heap_initial__size: 4G
      NEO4J_server_memory_heap_max__size: 4G
      NEO4J_server_memory_pagecache_size: 2G

  gradvek:
    image: gradvek/springdb-docker
    ports:
      - "3000:3000"
      - "8080:8080"